### ISSUE TITLE
ArticleBundle 3.0 without PHPCR and Elasticsearch

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluArticleBundle#690]
| Q | A
| --- | ---
| Bug? | no
| New Feature? | yes
| SuluArticleBundle Version | for 3.0

#### Related Pull Requests

 - https://github.com/sulu/SuluContentBundle/pull/213
 - https://github.com/sulu/SuluContentBundle/pull/212
 - https://github.com/sulu/SuluContentBundle/pull/211
 - https://github.com/sulu/SuluContentBundle/pull/210
 - https://github.com/sulu/SuluContentBundle/pull/205
 - https://github.com/sulu/SuluContentBundle/pull/206
 - https://github.com/sulu/SuluContentBundle/pull/208
 - https://github.com/sulu/SuluContentBundle/pull/193
 - https://github.com/sulu/SuluContentBundle/pull/190
 
#### Related Issues

 - Content Bundle Issues https://github.com/sulu/SuluContentBundle/milestone/3
   Not part of this PR and will be solved in ContentBundle itself

#### TODO

 - [ ] Tests
 - [ ] Documentation for `ArticleMapperInterface` as official endpoint for create and modify handler

#### New Bundle Structure

 - [x] Namespace: `Sulu\Article` under `src`
    - [x] Application
        - [x] Message
        - [x] MessageHandler
    - [x] Domain
        - [ ] Event (Domain Events, Activity)
             - [ ] ...
        - [x] Models
             - [x] Article
             - [x] ArticleDimensionContent
        - [x] Repository
             - [x] ArticleRepositoryInterface
    - [x] Infrastructure
        - [x] Sulu
             - [x] Admin
             - [x] Content
                 - [x] Providers (Smart, Sitemap, Link, Teaser)
                 - [ ] Content Types
             - [ ] Trash
                 - [ ] 🤔 
        - [x] Doctrine
             - [x] Repository
                 - [x] ArticleRepository
        - [x] Symfony
             - [x] HttpKernel
                 - [x] SuluArticleBundle
    - [x] UserInterface
        - [x] Controller
             - [x] ArticleController

#### Open

But not part of this Pull Request:

 - [x] Single Select Content Type
     - [ ] properties definitions
 - [x] Multi Select Content TypeType
     - [ ] properties definitions
 - [x] Smart Content TypeType
     - [ ] properties definitions
 - [x] Teaser Provider
 - [x] Link Provider
 - [x] Sitemap Provider
 - [ ] Permissions
 - [ ] Handling Types
 - [ ] Activities
 - [ ] Trash
 - [ ] Reference
